[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "ensec-cli"
version = "1.0.3"
description = "EncryptSecureDEC Open Source CLI"
requires-python = ">=3.10"
readme = "README.md"

dependencies = [
    "pycryptodome",
    "cryptography"
]
[tool.setuptools]
packages = ["ensec_cli"]

[project.scripts]
ensec = "ensec_cli.cli:main"